In [4]:
import pandas as pd 
import numpy as np
pd.set_option('display.max_columns', None)
data = pd.read_csv('2023.csv',thousands=',')
data

,Date,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,外陸資買進股數(不含外資自營商),外陸資賣出股數(不含外資自營商),外陸資買賣超股數(不含外資自營商),外資自營商買進股數,外資自營商賣出股數,外資自營商買賣超股數,投信買進股數,投信賣出股數,投信買賣超股數,自營商買賣超股數,自營商買進股數(自行買賣),自營商賣出股數(自行買賣),自營商買賣超股數(自行買賣),自營商買進股數(避險),自營商賣出股數(避險),自營商買賣超股數(避險),三大法人買賣超股數
0,20230302,2330,台積電,18017085,14320,9344352321,519,520,515,519,-,3,13697424,13543202,154222,0,0,0,164000,53544,110456,-708795,22000,629000,-607000,104684,206479,-101795,-444117
1,20230303,2330,台積電,24117189,22160,12510608773,524,525,516,516,-,3,14184220,19975993,-5791773,0,0,0,1138000,69000,1069000,-61768,73080,78000,-4920,124050,180898,-56848,-4784541
2,20230306,2330,台積電,24741125,20678,12883854256,520,524,517,521,+,5,16306272,16368865,-62593,0,0,0,1000000,56490,943510,2845632,2187340,21000,2166340,811008,131716,679292,3726549
3,20230307,2330,台積電,27650283,20595,14465320023,521,526,519,524,+,3,17915531,17838355,77176,0,0,0,1534000,43490,1490510,798515,410100,65000,345100,563318,109903,453415,2366201
4,20230308,2330,台積電,27077587,20504,14091713576,521,523,518,521,-,3,16230241,21258070,-5027829,0,0,0,218000,68000,150000,1668753,1789100,168000,1621100,287317,239664,47653,-3209076
5,20230309,2330,台積電,25639391,16497,13430582677,525,526,522,522,+,1,18488046,18693743,-205697,0,0,0,265000,61490,203510,197626,302000,51000,251000,99623,152997,-53374,195439
6,20230310,2330,台積電,25572403,46216,13122265260,515,516,511,513,-,9,11707421,19844934,-8137513,0,0,0,238000,80000,158000,-806093,24000,491000,-467000,80000,419093,-339093,-8785606
7,20230313,2330,台積電,22568740,24150,11608973891,513,518,509,516,+,3,14443979,12965582,1478397,0,0,0,115000,52530,62470,492329,695000,493000,202000,342611,52282,290329,2033196
8,20230314,2330,台積電,26599476,24848,13602260966,511,514,510,510,-,6,17695810,22319939,-4624129,0,0,0,310000,93000,217000,-54721,460000,440000,20000,134991,209712,-74721,-4461850
9,20230315,2330,台積電,24080361,21075,12350942139,515,516,510,511,+,1,14569735,16692396,-2122661,0,0,0,362143,77000,285143,-1430360,335000,1290000,-955000,256999,732359,-475360,-3267878
10,20230316,2330,台積電,23325664,33493,11809911840,505,510,504,505,X,0,12059093,17784889,-5725796,0,0,0,204000,33000,171000,312157,293000,209000,84000,426997,198840,228157,-5242639
11,20230317,2330,台積電,35872881,21217,18538033584,516,518,513,518,+,13,27542580,18979547,8563033,0,0,0,268000,2118123,-1850123,-50544,315000,311000,4000,102458,157002,-54544,6662366
12,20230320,2330,台積電,12752221,17709,6542889562,517,518,510,512,-,6,6429510,8173744,-1744234,0,0,0,58000,47000,11000,56870,120000,50000,70000,109000,122130,-13130,-1676364
13,20230321,2330,台積電,18519120,14094,9534730452,515,517,512,517,+,5,14940803,12561066,2379737,0,0,0,254000,32000,222000,90597,94000,157000,-63000,294797,141200,153597,2692334
14,20230322,2330,台積電,45681056,56483,24168561556,524,533,524,533,+,16,35694798,6086532,29608266,0,0,0,257006,73000,184006,333026,645997,448000,197997,346229,211200,135029,30125298
15,20230323,2330,台積電,28614856,35313,15307492846,528,539,528,538,+,5,19135324,9639544,9495780,0,0,0,799005,182000,617005,-586241,286000,689000,-403000,205759,389000,-183241,9526544
16,20230324,2330,台積電,22963771,24762,12348311773,536,539,535,539,+,1,14489182,8479332,6009850,0,0,0,2344979,372395,1972584,-153716,142000,334000,-192000,220484,182200,38284,7828718
17,20230327,2330,台積電,17170557,17484,9148085033,533,536,531,531,-,8,9399715,10637986,-1238271,0,0,0,45000,201000,-156000,280184,132000,75000,57000,307161,83977,223184,-1114087
18,20230328,2330,台積電,18327556,20744,9629323504,525,530,524,525,-,6,10992562,12459034,-1466472,0,0,0,62504,155520,-93016,-56726,65000,118000,-53000,191181,194907,-3726,-1616214
19,20230329,2330,台積電,17620195,15653,9329137251,533,533,525,530,+,5,14612421,9795846,4816575,0,0,0,108337,24520,83817,-425960,51000,507000,-456000,126694,96654,30040,4474432
20,20230330,2330,台積電,20380650,18171,10894446851,536,537,531,535,+,5,16398668,10674588,5724080,0,0,0,32000,131996,-99996,146845,208000,299000,-91000,312899,75054,237845,5770929
21,20230331,2330,台積電,24324776,15962,12997575231,538,538,532,533,-,2,20121986,16292211,3829775,0,0,0,60000,144520,-84520,757555,552000,97000,455000,317555,15000,302555,4502810
22,20230406,2330,台積電,26706549,19144,14130223516,530,531,526,530,-,3,22033223,19679864,2353359,0,0,0,60000,89000,-29000,-221335,54000,322398,-268398,139190,92127,47063,2103024
23,20230407,2330,台積電,11114272,10285,5903807797,535,535,529,531,+,1,8456655,6175281,2281374,0,0,0,147000,103000,44000,-94000,16000,110000,-94000,40000,40000,0,2231374
24,20230410,2330,台積電,8203168,11698,4350907176,533,533,528,529,-,2,5283579,4059556,1224023,0,0,0,19355,74520,-55165,-78588,12000,111000,-99000,68412,48000,20412,1090270

In [5]:
data['自營商買進股數']=data['自營商買進股數(自行買賣)'].fillna(0)+data['自營商買進股數(避險)'].fillna(0)
data['自營商賣出股數']=data['自營商賣出股數(自行買賣)'].fillna(0)+data['自營商賣出股數(避險)'].fillna(0)
data=data.drop(['證券代號','證券名稱','自營商買進股數(自行買賣)','自營商買進股數(避險)','自營商賣出股數(自行買賣)','自營商賣出股數(避險)','自營商買賣超股數(自行買賣)','自營商買賣超股數(避險)'],axis=1)
data

,Date,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,外陸資買進股數(不含外資自營商),外陸資賣出股數(不含外資自營商),外陸資買賣超股數(不含外資自營商),外資自營商買進股數,外資自營商賣出股數,外資自營商買賣超股數,投信買進股數,投信賣出股數,投信買賣超股數,自營商買賣超股數,三大法人買賣超股數,自營商買進股數,自營商賣出股數
0,20230302,18017085,14320,9344352321,519,520,515,519,-,3,13697424,13543202,154222,0,0,0,164000,53544,110456,-708795,-444117,126684,835479
1,20230303,24117189,22160,12510608773,524,525,516,516,-,3,14184220,19975993,-5791773,0,0,0,1138000,69000,1069000,-61768,-4784541,197130,258898
2,20230306,24741125,20678,12883854256,520,524,517,521,+,5,16306272,16368865,-62593,0,0,0,1000000,56490,943510,2845632,3726549,2998348,152716
3,20230307,27650283,20595,14465320023,521,526,519,524,+,3,17915531,17838355,77176,0,0,0,1534000,43490,1490510,798515,2366201,973418,174903
4,20230308,27077587,20504,14091713576,521,523,518,521,-,3,16230241,21258070,-5027829,0,0,0,218000,68000,150000,1668753,-3209076,2076417,407664
5,20230309,25639391,16497,13430582677,525,526,522,522,+,1,18488046,18693743,-205697,0,0,0,265000,61490,203510,197626,195439,401623,203997
6,20230310,25572403,46216,13122265260,515,516,511,513,-,9,11707421,19844934,-8137513,0,0,0,238000,80000,158000,-806093,-8785606,104000,910093
7,20230313,22568740,24150,11608973891,513,518,509,516,+,3,14443979,12965582,1478397,0,0,0,115000,52530,62470,492329,2033196,1037611,545282
8,20230314,26599476,24848,13602260966,511,514,510,510,-,6,17695810,22319939,-4624129,0,0,0,310000,93000,217000,-54721,-4461850,594991,649712
9,20230315,24080361,21075,12350942139,515,516,510,511,+,1,14569735,16692396,-2122661,0,0,0,362143,77000,285143,-1430360,-3267878,591999,2022359
10,20230316,23325664,33493,11809911840,505,510,504,505,X,0,12059093,17784889,-5725796,0,0,0,204000,33000,171000,312157,-5242639,719997,407840
11,20230317,35872881,21217,18538033584,516,518,513,518,+,13,27542580,18979547,8563033,0,0,0,268000,2118123,-1850123,-50544,6662366,417458,468002
12,20230320,12752221,17709,6542889562,517,518,510,512,-,6,6429510,8173744,-1744234,0,0,0,58000,47000,11000,56870,-1676364,229000,172130
13,20230321,18519120,14094,9534730452,515,517,512,517,+,5,14940803,12561066,2379737,0,0,0,254000,32000,222000,90597,2692334,388797,298200
14,20230322,45681056,56483,24168561556,524,533,524,533,+,16,35694798,6086532,29608266,0,0,0,257006,73000,184006,333026,30125298,992226,659200
15,20230323,28614856,35313,15307492846,528,539,528,538,+,5,19135324,9639544,9495780,0,0,0,799005,182000,617005,-586241,9526544,491759,1078000
16,20230324,22963771,24762,12348311773,536,539,535,539,+,1,14489182,8479332,6009850,0,0,0,2344979,372395,1972584,-153716,7828718,362484,516200
17,20230327,17170557,17484,9148085033,533,536,531,531,-,8,9399715,10637986,-1238271,0,0,0,45000,201000,-156000,280184,-1114087,439161,158977
18,20230328,18327556,20744,9629323504,525,530,524,525,-,6,10992562,12459034,-1466472,0,0,0,62504,155520,-93016,-56726,-1616214,256181,312907
19,20230329,17620195,15653,9329137251,533,533,525,530,+,5,14612421,9795846,4816575,0,0,0,108337,24520,83817,-425960,4474432,177694,603654
20,20230330,20380650,18171,10894446851,536,537,531,535,+,5,16398668,10674588,5724080,0,0,0,32000,131996,-99996,146845,5770929,520899,374054
21,20230331,24324776,15962,12997575231,538,538,532,533,-,2,20121986,16292211,3829775,0,0,0,60000,144520,-84520,757555,4502810,869555,112000
22,20230406,26706549,19144,14130223516,530,531,526,530,-,3,22033223,19679864,2353359,0,0,0,60000,89000,-29000,-221335,2103024,193190,414525
23,20230407,11114272,10285,5903807797,535,535,529,531,+,1,8456655,6175281,2281374,0,0,0,147000,103000,44000,-94000,2231374,56000,150000
24,20230410,8203168,11698,4350907176,533,533,528,529,-,2,5283579,4059556,1224023,0,0,0,19355,74520,-55165,-78588,1090270,80412,159000

In [6]:
data['外資買進股數']=data['外陸資買進股數(不含外資自營商)'].fillna(0)+data['外資自營商買進股數'].fillna(0)
data['外資賣出股數']=data['外陸資賣出股數(不含外資自營商)'].fillna(0)+data['外資自營商賣出股數'].fillna(0)
data['外資買賣超股數']=data['外陸資買賣超股數(不含外資自營商)'].fillna(0)+data['外資自營商買賣超股數'].fillna(0)
data

,Date,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,外陸資買進股數(不含外資自營商),外陸資賣出股數(不含外資自營商),外陸資買賣超股數(不含外資自營商),外資自營商買進股數,外資自營商賣出股數,外資自營商買賣超股數,投信買進股數,投信賣出股數,投信買賣超股數,自營商買賣超股數,三大法人買賣超股數,自營商買進股數,自營商賣出股數,外資買進股數,外資賣出股數,外資買賣超股數
0,20230302,18017085,14320,9344352321,519,520,515,519,-,3,13697424,13543202,154222,0,0,0,164000,53544,110456,-708795,-444117,126684,835479,13697424,13543202,154222
1,20230303,24117189,22160,12510608773,524,525,516,516,-,3,14184220,19975993,-5791773,0,0,0,1138000,69000,1069000,-61768,-4784541,197130,258898,14184220,19975993,-5791773
2,20230306,24741125,20678,12883854256,520,524,517,521,+,5,16306272,16368865,-62593,0,0,0,1000000,56490,943510,2845632,3726549,2998348,152716,16306272,16368865,-62593
3,20230307,27650283,20595,14465320023,521,526,519,524,+,3,17915531,17838355,77176,0,0,0,1534000,43490,1490510,798515,2366201,973418,174903,17915531,17838355,77176
4,20230308,27077587,20504,14091713576,521,523,518,521,-,3,16230241,21258070,-5027829,0,0,0,218000,68000,150000,1668753,-3209076,2076417,407664,16230241,21258070,-5027829
5,20230309,25639391,16497,13430582677,525,526,522,522,+,1,18488046,18693743,-205697,0,0,0,265000,61490,203510,197626,195439,401623,203997,18488046,18693743,-205697
6,20230310,25572403,46216,13122265260,515,516,511,513,-,9,11707421,19844934,-8137513,0,0,0,238000,80000,158000,-806093,-8785606,104000,910093,11707421,19844934,-8137513
7,20230313,22568740,24150,11608973891,513,518,509,516,+,3,14443979,12965582,1478397,0,0,0,115000,52530,62470,492329,2033196,1037611,545282,14443979,12965582,1478397
8,20230314,26599476,24848,13602260966,511,514,510,510,-,6,17695810,22319939,-4624129,0,0,0,310000,93000,217000,-54721,-4461850,594991,649712,17695810,22319939,-4624129
9,20230315,24080361,21075,12350942139,515,516,510,511,+,1,14569735,16692396,-2122661,0,0,0,362143,77000,285143,-1430360,-3267878,591999,2022359,14569735,16692396,-2122661
10,20230316,23325664,33493,11809911840,505,510,504,505,X,0,12059093,17784889,-5725796,0,0,0,204000,33000,171000,312157,-5242639,719997,407840,12059093,17784889,-5725796
11,20230317,35872881,21217,18538033584,516,518,513,518,+,13,27542580,18979547,8563033,0,0,0,268000,2118123,-1850123,-50544,6662366,417458,468002,27542580,18979547,8563033
12,20230320,12752221,17709,6542889562,517,518,510,512,-,6,6429510,8173744,-1744234,0,0,0,58000,47000,11000,56870,-1676364,229000,172130,6429510,8173744,-1744234
13,20230321,18519120,14094,9534730452,515,517,512,517,+,5,14940803,12561066,2379737,0,0,0,254000,32000,222000,90597,2692334,388797,298200,14940803,12561066,2379737
14,20230322,45681056,56483,24168561556,524,533,524,533,+,16,35694798,6086532,29608266,0,0,0,257006,73000,184006,333026,30125298,992226,659200,35694798,6086532,29608266
15,20230323,28614856,35313,15307492846,528,539,528,538,+,5,19135324,9639544,9495780,0,0,0,799005,182000,617005,-586241,9526544,491759,1078000,19135324,9639544,9495780
16,20230324,22963771,24762,12348311773,536,539,535,539,+,1,14489182,8479332,6009850,0,0,0,2344979,372395,1972584,-153716,7828718,362484,516200,14489182,8479332,6009850
17,20230327,17170557,17484,9148085033,533,536,531,531,-,8,9399715,10637986,-1238271,0,0,0,45000,201000,-156000,280184,-1114087,439161,158977,9399715,10637986,-1238271
18,20230328,18327556,20744,9629323504,525,530,524,525,-,6,10992562,12459034,-1466472,0,0,0,62504,155520,-93016,-56726,-1616214,256181,312907,10992562,12459034,-1466472
19,20230329,17620195,15653,9329137251,533,533,525,530,+,5,14612421,9795846,4816575,0,0,0,108337,24520,83817,-425960,4474432,177694,603654,14612421,9795846,4816575
20,20230330,20380650,18171,10894446851,536,537,531,535,+,5,16398668,10674588,5724080,0,0,0,32000,131996,-99996,146845,5770929,520899,374054,16398668,10674588,5724080
21,20230331,24324776,15962,12997575231,538,538,532,533,-,2,20121986,16292211,3829775,0,0,0,60000,144520,-84520,757555,4502810,869555,112000,20121986,16292211,3829775
22,20230406,26706549,19144,14130223516,530,531,526,530,-,3,22033223,19679864,2353359,0,0,0,60000,89000,-29000,-221335,2103024,193190,414525,22033223,19679864,2353359
23,20230407,11114272,10285,5903807797,535,535,529,531,+,1,8456655,6175281,2281374,0,0,0,147000,103000,44000,-94000,2231374,56000,150000,8456655,6175281,2281374
24,20230410,8203168,11698,4350907176,533,533,528,529,-,2,5283579,4059556,1224023,0,0,0,19355,74520,-55165,-78588,1090270,80412,159000,5283579,4059556,1224023

In [8]:
data=data.drop(['外陸資買進股數(不含外資自營商)','外陸資賣出股數(不含外資自營商)','外陸資買賣超股數(不含外資自營商)',
               '外資自營商買進股數','外資自營商賣出股數','外資自營商買賣超股數'],axis=1)
data

,Date,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,投信買進股數,投信賣出股數,投信買賣超股數,自營商買賣超股數,三大法人買賣超股數,自營商買進股數,自營商賣出股數,外資買進股數,外資賣出股數,外資買賣超股數
0,20230302,18017085,14320,9344352321,519,520,515,519,-,3,164000,53544,110456,-708795,-444117,126684,835479,13697424,13543202,154222
1,20230303,24117189,22160,12510608773,524,525,516,516,-,3,1138000,69000,1069000,-61768,-4784541,197130,258898,14184220,19975993,-5791773
2,20230306,24741125,20678,12883854256,520,524,517,521,+,5,1000000,56490,943510,2845632,3726549,2998348,152716,16306272,16368865,-62593
3,20230307,27650283,20595,14465320023,521,526,519,524,+,3,1534000,43490,1490510,798515,2366201,973418,174903,17915531,17838355,77176
4,20230308,27077587,20504,14091713576,521,523,518,521,-,3,218000,68000,150000,1668753,-3209076,2076417,407664,16230241,21258070,-5027829
5,20230309,25639391,16497,13430582677,525,526,522,522,+,1,265000,61490,203510,197626,195439,401623,203997,18488046,18693743,-205697
6,20230310,25572403,46216,13122265260,515,516,511,513,-,9,238000,80000,158000,-806093,-8785606,104000,910093,11707421,19844934,-8137513
7,20230313,22568740,24150,11608973891,513,518,509,516,+,3,115000,52530,62470,492329,2033196,1037611,545282,14443979,12965582,1478397
8,20230314,26599476,24848,13602260966,511,514,510,510,-,6,310000,93000,217000,-54721,-4461850,594991,649712,17695810,22319939,-4624129
9,20230315,24080361,21075,12350942139,515,516,510,511,+,1,362143,77000,285143,-1430360,-3267878,591999,2022359,14569735,16692396,-2122661
10,20230316,23325664,33493,11809911840,505,510,504,505,X,0,204000,33000,171000,312157,-5242639,719997,407840,12059093,17784889,-5725796
11,20230317,35872881,21217,18538033584,516,518,513,518,+,13,268000,2118123,-1850123,-50544,6662366,417458,468002,27542580,18979547,8563033
12,20230320,12752221,17709,6542889562,517,518,510,512,-,6,58000,47000,11000,56870,-1676364,229000,172130,6429510,8173744,-1744234
13,20230321,18519120,14094,9534730452,515,517,512,517,+,5,254000,32000,222000,90597,2692334,388797,298200,14940803,12561066,2379737
14,20230322,45681056,56483,24168561556,524,533,524,533,+,16,257006,73000,184006,333026,30125298,992226,659200,35694798,6086532,29608266
15,20230323,28614856,35313,15307492846,528,539,528,538,+,5,799005,182000,617005,-586241,9526544,491759,1078000,19135324,9639544,9495780
16,20230324,22963771,24762,12348311773,536,539,535,539,+,1,2344979,372395,1972584,-153716,7828718,362484,516200,14489182,8479332,6009850
17,20230327,17170557,17484,9148085033,533,536,531,531,-,8,45000,201000,-156000,280184,-1114087,439161,158977,9399715,10637986,-1238271
18,20230328,18327556,20744,9629323504,525,530,524,525,-,6,62504,155520,-93016,-56726,-1616214,256181,312907,10992562,12459034,-1466472
19,20230329,17620195,15653,9329137251,533,533,525,530,+,5,108337,24520,83817,-425960,4474432,177694,603654,14612421,9795846,4816575
20,20230330,20380650,18171,10894446851,536,537,531,535,+,5,32000,131996,-99996,146845,5770929,520899,374054,16398668,10674588,5724080
21,20230331,24324776,15962,12997575231,538,538,532,533,-,2,60000,144520,-84520,757555,4502810,869555,112000,20121986,16292211,3829775
22,20230406,26706549,19144,14130223516,530,531,526,530,-,3,60000,89000,-29000,-221335,2103024,193190,414525,22033223,19679864,2353359
23,20230407,11114272,10285,5903807797,535,535,529,531,+,1,147000,103000,44000,-94000,2231374,56000,150000,8456655,6175281,2281374
24,20230410,8203168,11698,4350907176,533,533,528,529,-,2,19355,74520,-55165,-78588,1090270,80412,159000,5283579,4059556,1224023

In [9]:
data.isnull().sum()

Date         0
成交股數         0
成交筆數         0
成交金額         0
開盤價          0
最高價          0
最低價          0
收盤價          0
漲跌(+/-)      0
漲跌價差         0
投信買進股數       0
投信賣出股數       0
投信買賣超股數      0
自營商買賣超股數     0
三大法人買賣超股數    0
自營商買進股數      0
自營商賣出股數      0
外資買進股數       0
外資賣出股數       0
外資買賣超股數      0
dtype: int64

In [10]:
data['DateTime']=pd.to_datetime(data['Date'], format='%Y%m%d')
cols=data.columns.tolist()
cols=cols[-1:]+cols[:-1]
data=data[cols]
data.rename(columns={'成交股數': 'Volume', '成交筆數': 'Transaction', '成交金額': 'Value', '開盤價': 'Open', '最高價': 'High', '最低價': 'Low', '收盤價': 'Close', '漲跌(+/-)': 'Dir', '漲跌價差': 'Change', '外資買進股數': 'ForeignBuy', '外資賣出股數': 'ForeignSell', '外資買賣超股數': 'ForeignNet', '投信買進股數': 'TrustBuy', '投信賣出股數': 'TrustSell', '投信買賣超股數': 'TrustNet', '自營商買賣超股數': 'DealerNet', '自營商買進股數': 'DealerBuy', '自營商賣出股數': 'DealerSell', '三大法人買賣超股數': 'InvestorsNet', '本益比': 'PE-Ratio', '股價淨值比': 'PBR', '殖利率': 'Yield'}, inplace=True)
data

,DateTime,Date,Volume,Transaction,Value,Open,High,Low,Close,Dir,Change,TrustBuy,TrustSell,TrustNet,DealerNet,InvestorsNet,DealerBuy,DealerSell,ForeignBuy,ForeignSell,ForeignNet
0,2023-03-02,20230302,18017085,14320,9344352321,519,520,515,519,-,3,164000,53544,110456,-708795,-444117,126684,835479,13697424,13543202,154222
1,2023-03-03,20230303,24117189,22160,12510608773,524,525,516,516,-,3,1138000,69000,1069000,-61768,-4784541,197130,258898,14184220,19975993,-5791773
2,2023-03-06,20230306,24741125,20678,12883854256,520,524,517,521,+,5,1000000,56490,943510,2845632,3726549,2998348,152716,16306272,16368865,-62593
3,2023-03-07,20230307,27650283,20595,14465320023,521,526,519,524,+,3,1534000,43490,1490510,798515,2366201,973418,174903,17915531,17838355,77176
4,2023-03-08,20230308,27077587,20504,14091713576,521,523,518,521,-,3,218000,68000,150000,1668753,-3209076,2076417,407664,16230241,21258070,-5027829
5,2023-03-09,20230309,25639391,16497,13430582677,525,526,522,522,+,1,265000,61490,203510,197626,195439,401623,203997,18488046,18693743,-205697
6,2023-03-10,20230310,25572403,46216,13122265260,515,516,511,513,-,9,238000,80000,158000,-806093,-8785606,104000,910093,11707421,19844934,-8137513
7,2023-03-13,20230313,22568740,24150,11608973891,513,518,509,516,+,3,115000,52530,62470,492329,2033196,1037611,545282,14443979,12965582,1478397
8,2023-03-14,20230314,26599476,24848,13602260966,511,514,510,510,-,6,310000,93000,217000,-54721,-4461850,594991,649712,17695810,22319939,-4624129
9,2023-03-15,20230315,24080361,21075,12350942139,515,516,510,511,+,1,362143,77000,285143,-1430360,-3267878,591999,2022359,14569735,16692396,-2122661
10,2023-03-16,20230316,23325664,33493,11809911840,505,510,504,505,X,0,204000,33000,171000,312157,-5242639,719997,407840,12059093,17784889,-5725796
11,2023-03-17,20230317,35872881,21217,18538033584,516,518,513,518,+,13,268000,2118123,-1850123,-50544,6662366,417458,468002,27542580,18979547,8563033
12,2023-03-20,20230320,12752221,17709,6542889562,517,518,510,512,-,6,58000,47000,11000,56870,-1676364,229000,172130,6429510,8173744,-1744234
13,2023-03-21,20230321,18519120,14094,9534730452,515,517,512,517,+,5,254000,32000,222000,90597,2692334,388797,298200,14940803,12561066,2379737
14,2023-03-22,20230322,45681056,56483,24168561556,524,533,524,533,+,16,257006,73000,184006,333026,30125298,992226,659200,35694798,6086532,29608266
15,2023-03-23,20230323,28614856,35313,15307492846,528,539,528,538,+,5,799005,182000,617005,-586241,9526544,491759,1078000,19135324,9639544,9495780
16,2023-03-24,20230324,22963771,24762,12348311773,536,539,535,539,+,1,2344979,372395,1972584,-153716,7828718,362484,516200,14489182,8479332,6009850
17,2023-03-27,20230327,17170557,17484,9148085033,533,536,531,531,-,8,45000,201000,-156000,280184,-1114087,439161,158977,9399715,10637986,-1238271
18,2023-03-28,20230328,18327556,20744,9629323504,525,530,524,525,-,6,62504,155520,-93016,-56726,-1616214,256181,312907,10992562,12459034,-1466472
19,2023-03-29,20230329,17620195,15653,9329137251,533,533,525,530,+,5,108337,24520,83817,-425960,4474432,177694,603654,14612421,9795846,4816575
20,2023-03-30,20230330,20380650,18171,10894446851,536,537,531,535,+,5,32000,131996,-99996,146845,5770929,520899,374054,16398668,10674588,5724080
21,2023-03-31,20230331,24324776,15962,12997575231,538,538,532,533,-,2,60000,144520,-84520,757555,4502810,869555,112000,20121986,16292211,3829775
22,2023-04-06,20230406,26706549,19144,14130223516,530,531,526,530,-,3,60000,89000,-29000,-221335,2103024,193190,414525,22033223,19679864,2353359
23,2023-04-07,20230407,11114272,10285,5903807797,535,535,529,531,+,1,147000,103000,44000,-94000,2231374,56000,150000,8456655,6175281,2281374
24,2023-04-10,20230410,8203168,11698,4350907176,533,533,528,529,-,2,19355,74520,-55165,-78588,1090270,80412,159000,5283579,4059556,1224023

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   DateTime      25 non-null     datetime64[ns]
 1   Date          25 non-null     int64
 2   Volume        25 non-null     int64
 3   Transaction   25 non-null     int64
 4   Value         25 non-null     int64
 5   Open          25 non-null     int64
 6   High          25 non-null     int64
 7   Low           25 non-null     int64
 8   Close         25 non-null     int64
 9   Dir           25 non-null     object
 10  Change        25 non-null     int64
 11  TrustBuy      25 non-null     int64
 12  TrustSell     25 non-null     int64
 13  TrustNet      25 non-null     int64
 14  DealerNet     25 non-null     int64
 15  InvestorsNet  25 non-null     int64
 16  DealerBuy     25 non-null     int64
 17  DealerSell    25 non-null     int64
 18  ForeignBuy    25 non-null     int64
 19  ForeignSell   25 non-null     int64
 20  ForeignNet    25 non-null     int64
dtypes: datetime64[ns](1), int64(19), object(1)
memory usage: 4.2+ KB

In [12]:
data['Volume']=(data['Volume']/1000).astype(int)
data['ForeignBuy']=(data['ForeignBuy']/1000).astype(int)
data['ForeignSell']=(data['ForeignSell']/1000).astype(int)
data['ForeignNet']=(data['ForeignNet']/1000).astype(int)
data['TrustBuy']=(data['TrustBuy']/1000).astype(int)
data['TrustSell']=(data['TrustSell']/1000).astype(int)
data['TrustNet']=(data['TrustNet']/1000).astype(int)
data['DealerNet']=(data['DealerNet']/1000).astype(int)
data['DealerBuy']=(data['DealerBuy']/1000).astype(int)
data['DealerSell']=(data['DealerSell']/1000).astype(int)
data['InvestorsNet']=(data['InvestorsNet']/1000).astype(int)

data=data.drop(['Value'],axis=1)
data

,DateTime,Date,Volume,Transaction,Open,High,Low,Close,Dir,Change,TrustBuy,TrustSell,TrustNet,DealerNet,InvestorsNet,DealerBuy,DealerSell,ForeignBuy,ForeignSell,ForeignNet
0,2023-03-02,20230302,18017,14320,519,520,515,519,-,3,164,53,110,-708,-444,126,835,13697,13543,154
1,2023-03-03,20230303,24117,22160,524,525,516,516,-,3,1138,69,1069,-61,-4784,197,258,14184,19975,-5791
2,2023-03-06,20230306,24741,20678,520,524,517,521,+,5,1000,56,943,2845,3726,2998,152,16306,16368,-62
3,2023-03-07,20230307,27650,20595,521,526,519,524,+,3,1534,43,1490,798,2366,973,174,17915,17838,77
4,2023-03-08,20230308,27077,20504,521,523,518,521,-,3,218,68,150,1668,-3209,2076,407,16230,21258,-5027
5,2023-03-09,20230309,25639,16497,525,526,522,522,+,1,265,61,203,197,195,401,203,18488,18693,-205
6,2023-03-10,20230310,25572,46216,515,516,511,513,-,9,238,80,158,-806,-8785,104,910,11707,19844,-8137
7,2023-03-13,20230313,22568,24150,513,518,509,516,+,3,115,52,62,492,2033,1037,545,14443,12965,1478
8,2023-03-14,20230314,26599,24848,511,514,510,510,-,6,310,93,217,-54,-4461,594,649,17695,22319,-4624
9,2023-03-15,20230315,24080,21075,515,516,510,511,+,1,362,77,285,-1430,-3267,591,2022,14569,16692,-2122
10,2023-03-16,20230316,23325,33493,505,510,504,505,X,0,204,33,171,312,-5242,719,407,12059,17784,-5725
11,2023-03-17,20230317,35872,21217,516,518,513,518,+,13,268,2118,-1850,-50,6662,417,468,27542,18979,8563
12,2023-03-20,20230320,12752,17709,517,518,510,512,-,6,58,47,11,56,-1676,229,172,6429,8173,-1744
13,2023-03-21,20230321,18519,14094,515,517,512,517,+,5,254,32,222,90,2692,388,298,14940,12561,2379
14,2023-03-22,20230322,45681,56483,524,533,524,533,+,16,257,73,184,333,30125,992,659,35694,6086,29608
15,2023-03-23,20230323,28614,35313,528,539,528,538,+,5,799,182,617,-586,9526,491,1078,19135,9639,9495
16,2023-03-24,20230324,22963,24762,536,539,535,539,+,1,2344,372,1972,-153,7828,362,516,14489,8479,6009
17,2023-03-27,20230327,17170,17484,533,536,531,531,-,8,45,201,-156,280,-1114,439,158,9399,10637,-1238
18,2023-03-28,20230328,18327,20744,525,530,524,525,-,6,62,155,-93,-56,-1616,256,312,10992,12459,-1466
19,2023-03-29,20230329,17620,15653,533,533,525,530,+,5,108,24,83,-425,4474,177,603,14612,9795,4816
20,2023-03-30,20230330,20380,18171,536,537,531,535,+,5,32,131,-99,146,5770,520,374,16398,10674,5724
21,2023-03-31,20230331,24324,15962,538,538,532,533,-,2,60,144,-84,757,4502,869,112,20121,16292,3829
22,2023-04-06,20230406,26706,19144,530,531,526,530,-,3,60,89,-29,-221,2103,193,414,22033,19679,2353
23,2023-04-07,20230407,11114,10285,535,535,529,531,+,1,147,103,44,-94,2231,56,150,8456,6175,2281
24,2023-04-10,20230410,8203,11698,533,533,528,529,-,2,19,74,-55,-78,1090,80,159,5283,4059,1224