In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = pd.read_csv('df2330_13to22.csv',thousands=',')
data

,Date,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,...,殖利率,自營商買進股數(自行買賣),自營商賣出股數(自行買賣),自營商買賣超股數(自行買賣),自營商買進股數(避險),自營商賣出股數(避險),自營商買賣超股數(避險),外陸資買進股數(不含外資自營商),外陸資賣出股數(不含外資自營商),外陸資買賣超股數(不含外資自營商)
0,20130102,40647121,14353,4021304950,97.6,99.9,97.1,99.6,+,2.6,...,3.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20130103,44335846,12616,4472175100,100.5,102.0,100.0,101.0,+,1.4,...,2.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20130104,39502577,10276,3980403777,100.5,101.5,100.0,101.5,+,0.5,...,2.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20130107,42328657,9042,4237769552,101.0,101.0,99.1,100.5,-,1.0,...,2.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20130108,31218717,9463,3100841808,99.6,100.0,98.9,99.7,-,0.8,...,3.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,20221226,9152790,16718,4171194858,454.0,457.0,453.5,456.5,+,1.5,...,2.41,199000.0,369000.0,-170000.0,207949.0,100104.0,107845.0,3755652.0,4793306.0,-1037654.0
2448,20221227,10486219,13482,4820155221,458.0,462.5,457.0,457.0,+,0.5,...,2.41,59000.0,35000.0,24000.0,165188.0,251158.0,-85970.0,5166242.0,4411593.0,754649.0
2449,20221228,34823492,59400,15643266841,451.0,452.0,446.0,451.0,-,6.0,...,2.44,64000.0,1592000.0,-1528000.0,609000.0,820234.0,-211234.0,6736524.0,22365973.0,-15629449.0
2450,20221229,25596357,34637,11400284554,444.0,449.5,442.5,446.0,-,5.0,...,2.47,647000.0,121000.0,526000.0,767000.0,124668.0,642332.0,13201405.0,19100242.0,-5898837.0
2451,20221230,22297604,23086,10079102379,455.0,456.5,448.5,448.5,+,2.5,...,2.45,272000.0,255100.0,16900.0,620394.0,97504.0,522890.0,13616579.0,13782228.0,-165649.0

In [3]:
data.dtypes

Date                   int64
成交股數                   int64
成交筆數                   int64
成交金額                   int64
開盤價                  float64
最高價                  float64
最低價                  float64
收盤價                  float64
漲跌(+/-)               object
漲跌價差                 float64
外資買進股數               float64
外資賣出股數               float64
外資買賣超股數              float64
投信買進股數                 int64
投信賣出股數                 int64
投信買賣超股數                int64
自營商買賣超股數               int64
自營商買進股數              float64
自營商賣出股數              float64
三大法人買賣超股數              int64
本益比                  float64
股價淨值比                float64
殖利率                  float64
自營商買進股數(自行買賣)        float64
自營商賣出股數(自行買賣)        float64
自營商買賣超股數(自行買賣)       float64
自營商買進股數(避險)          float64
自營商賣出股數(避險)          float64
自營商買賣超股數(避險)         float64
外陸資買進股數(不含外資自營商)     float64
外陸資賣出股數(不含外資自營商)     float64
外陸資買賣超股數(不含外資自營商)    float64
dtype: object

In [4]:
data['自營商買進tmpsum']=data['自營商買進股數(自行買賣)'].fillna(0)+data['自營商買進股數(避險)'].fillna(0)
data['自營商賣出tmpsum']=data['自營商賣出股數(自行買賣)'].fillna(0)+data['自營商賣出股數(避險)'].fillna(0)

In [ ]:
data=data.drop(['自營商買進股數(自行買賣)','自營商買進股數(避險)','自營商賣出股數(自行買賣)','自營商賣出股數(避險)'],axis=1)

In [5]:
data['自營商買進股數'].fillna(data['自營商買進tmpsum'])
data['自營商賣出股數'].fillna(data['自營商賣出tmpsum'])
data

,Date,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,...,自營商賣出股數(自行買賣),自營商買賣超股數(自行買賣),自營商買進股數(避險),自營商賣出股數(避險),自營商買賣超股數(避險),外陸資買進股數(不含外資自營商),外陸資賣出股數(不含外資自營商),外陸資買賣超股數(不含外資自營商),自營商買進tmpsum,自營商賣出tmpsum
0,20130102,40647121,14353,4021304950,97.6,99.9,97.1,99.6,+,2.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1,20130103,44335846,12616,4472175100,100.5,102.0,100.0,101.0,+,1.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2,20130104,39502577,10276,3980403777,100.5,101.5,100.0,101.5,+,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,20130107,42328657,9042,4237769552,101.0,101.0,99.1,100.5,-,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
4,20130108,31218717,9463,3100841808,99.6,100.0,98.9,99.7,-,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,20221226,9152790,16718,4171194858,454.0,457.0,453.5,456.5,+,1.5,...,369000.0,-170000.0,207949.0,100104.0,107845.0,3755652.0,4793306.0,-1037654.0,406949.0,469104.0
2448,20221227,10486219,13482,4820155221,458.0,462.5,457.0,457.0,+,0.5,...,35000.0,24000.0,165188.0,251158.0,-85970.0,5166242.0,4411593.0,754649.0,224188.0,286158.0
2449,20221228,34823492,59400,15643266841,451.0,452.0,446.0,451.0,-,6.0,...,1592000.0,-1528000.0,609000.0,820234.0,-211234.0,6736524.0,22365973.0,-15629449.0,673000.0,2412234.0
2450,20221229,25596357,34637,11400284554,444.0,449.5,442.5,446.0,-,5.0,...,121000.0,526000.0,767000.0,124668.0,642332.0,13201405.0,19100242.0,-5898837.0,1414000.0,245668.0
2451,20221230,22297604,23086,10079102379,455.0,456.5,448.5,448.5,+,2.5,...,255100.0,16900.0,620394.0,97504.0,522890.0,13616579.0,13782228.0,-165649.0,892394.0,352604.0

In [6]:
data

,Date,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,...,自營商賣出股數(自行買賣),自營商買賣超股數(自行買賣),自營商買進股數(避險),自營商賣出股數(避險),自營商買賣超股數(避險),外陸資買進股數(不含外資自營商),外陸資賣出股數(不含外資自營商),外陸資買賣超股數(不含外資自營商),自營商買進tmpsum,自營商賣出tmpsum
0,20130102,40647121,14353,4021304950,97.6,99.9,97.1,99.6,+,2.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1,20130103,44335846,12616,4472175100,100.5,102.0,100.0,101.0,+,1.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2,20130104,39502577,10276,3980403777,100.5,101.5,100.0,101.5,+,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,20130107,42328657,9042,4237769552,101.0,101.0,99.1,100.5,-,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
4,20130108,31218717,9463,3100841808,99.6,100.0,98.9,99.7,-,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,20221226,9152790,16718,4171194858,454.0,457.0,453.5,456.5,+,1.5,...,369000.0,-170000.0,207949.0,100104.0,107845.0,3755652.0,4793306.0,-1037654.0,406949.0,469104.0
2448,20221227,10486219,13482,4820155221,458.0,462.5,457.0,457.0,+,0.5,...,35000.0,24000.0,165188.0,251158.0,-85970.0,5166242.0,4411593.0,754649.0,224188.0,286158.0
2449,20221228,34823492,59400,15643266841,451.0,452.0,446.0,451.0,-,6.0,...,1592000.0,-1528000.0,609000.0,820234.0,-211234.0,6736524.0,22365973.0,-15629449.0,673000.0,2412234.0
2450,20221229,25596357,34637,11400284554,444.0,449.5,442.5,446.0,-,5.0,...,121000.0,526000.0,767000.0,124668.0,642332.0,13201405.0,19100242.0,-5898837.0,1414000.0,245668.0
2451,20221230,22297604,23086,10079102379,455.0,456.5,448.5,448.5,+,2.5,...,255100.0,16900.0,620394.0,97504.0,522890.0,13616579.0,13782228.0,-165649.0,892394.0,352604.0

In [7]:
data=data.drop(['自營商買進股數(自行買賣)','自營商買進股數(避險)','自營商賣出股數(自行買賣)','自營商賣出股數(避險)','自營商買進tmpsum','自營商賣出tmpsum'],axis=1)

In [8]:
data

,Date,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,...,自營商賣出股數,三大法人買賣超股數,本益比,股價淨值比,殖利率,自營商買賣超股數(自行買賣),自營商買賣超股數(避險),外陸資買進股數(不含外資自營商),外陸資賣出股數(不含外資自營商),外陸資買賣超股數(不含外資自營商)
0,20130102,40647121,14353,4021304950,97.6,99.9,97.1,99.6,+,2.6,...,1650000.0,15108173,16.54,3.83,3.01,NaN,NaN,NaN,NaN,NaN
1,20130103,44335846,12616,4472175100,100.5,102.0,100.0,101.0,+,1.4,...,2579000.0,14298188,16.78,3.88,2.97,NaN,NaN,NaN,NaN,NaN
2,20130104,39502577,10276,3980403777,100.5,101.5,100.0,101.5,+,0.5,...,1156000.0,9042611,16.86,3.90,2.96,NaN,NaN,NaN,NaN,NaN
3,20130107,42328657,9042,4237769552,101.0,101.0,99.1,100.5,-,1.0,...,1321000.0,-1511300,16.69,3.86,2.99,NaN,NaN,NaN,NaN,NaN
4,20130108,31218717,9463,3100841808,99.6,100.0,98.9,99.7,-,0.8,...,829000.0,1034826,16.56,3.83,3.01,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,20221226,9152790,16718,4171194858,454.0,457.0,453.5,456.5,+,1.5,...,NaN,-1168837,13.35,4.32,2.41,-170000.0,107845.0,3755652.0,4793306.0,-1037654.0
2448,20221227,10486219,13482,4820155221,458.0,462.5,457.0,457.0,+,0.5,...,NaN,753909,13.36,4.33,2.41,24000.0,-85970.0,5166242.0,4411593.0,754649.0
2449,20221228,34823492,59400,15643266841,451.0,452.0,446.0,451.0,-,6.0,...,NaN,-17427683,13.19,4.27,2.44,-1528000.0,-211234.0,6736524.0,22365973.0,-15629449.0
2450,20221229,25596357,34637,11400284554,444.0,449.5,442.5,446.0,-,5.0,...,NaN,-4854205,13.04,4.22,2.47,526000.0,642332.0,13201405.0,19100242.0,-5898837.0
2451,20221230,22297604,23086,10079102379,455.0,456.5,448.5,448.5,+,2.5,...,NaN,132141,13.11,4.25,2.45,16900.0,522890.0,13616579.0,13782228.0,-165649.0